# Generated by Django 5.2.7 on 2025-10-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_searchresult_searchcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='NASASearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nasa_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('image_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
                ('center', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('media_type', models.CharField(default='image', max_length=50)),
                ('search_query', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, unique=True)),
                ('search_count', models.IntegerField(default=1)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
